fix(univention-ox-connector-task-management): Fix remove_from_morgue
remove_from_morgue operated on an iterator from another function that
opened its own session so that deleting one of these objects resulted in
traceback. Saving those objects in a list before removal fixes the
problem.

root@master:~# univention-ox-connector-task-management remove-from-morgue --obj-id=470bf70a-28d8-40a2-b0a3-dfd65c9e15f1
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/univention/ox/provisioning/db.py", line 1054, in <module>
    args.func(args)
  File "/usr/lib/python3.9/site-packages/univention/ox/provisioning/db.py", line 957, in _call
    func(**params)
  File "/usr/lib/python3.9/site-packages/univention/ox/provisioning/db.py", line 647, in remove_from_morgue
    db_session.delete(error)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2537, in delete
    self._delete_impl(state, instance, head=True)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2549, in _delete_impl
    to_attach = self._before_attach(state, obj)
  File "/usr/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3141, in _before_attach
    raise sa_exc.InvalidRequestError(
sqlalchemy.exc.InvalidRequestError: Object '<Dead at 0x7f400718d580>' is already attached to session '2' (this is '1')

Issue: #0