fix(ox-connector): Task management CLI did not handle Path well
There was a breaking change in Python3.10. inspect.signature returns now
strings instead of types. This lead to:

$ univention-ox-connector-task-management add-old --path /var/lib/.../some.json
Traceback (most recent call last):
  File "/usr/local/share/ox-connector/resources/univention-ox-connector-task-management", line 440, in <module>
    _add_action(subparsers, add_task)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/share/ox-connector/resources/univention-ox-connector-task-management", line 93, in _add_action
    subparser.add_argument(name, **arg_params)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/argparse.py", line 1490, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'Path' is not callable

Issue: #0