fix: logger.warn does not exist anymore
Some code used the deprecated logger.warn instead of logger.warning.
While this works for the built-in logger of Python, loguru does not
suppoert this:

Traceback (most recent call last):
  File "/consumer.py", line 495, in <module>
    main()
    └ <function main at 0x7fccac6568e0>
  File "/consumer.py", line 491, in main
    asyncio.run(_run_consumer_with_guard())
    │       │   └ <function _run_consumer_with_guard at 0x7fccac655b20>
    │       └ <function run at 0x7fccafb136a0>
    └ <module 'asyncio' from '/usr/lib/python3.13/asyncio/__init__.py'>
  File "/usr/lib/python3.13/asyncio/runners.py", line 195, in run
    return runner.run(main)
           │      │   └ <coroutine object _run_consumer_with_guard at 0x7fccac6369d0>
           │      └ <function Runner.run at 0x7fccaed97600>
           └ <asyncio.runners.Runner object at 0x7fccac64d160>
  File "/usr/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<_run_consumer_with_guard() running at /consumer.py:484> wait_for=<Future pending cb=[Task.t...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7fccaed951c0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7fccac64d160>
  File "/usr/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fccaed95120>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fccaed96f20>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/lib/python3.13/asyncio/base_events.py", line 2042, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fccaef36020>
    └ <Handle Task.task_wakeup()>
  File "/usr/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle Task.task_wakeup()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle Task.task_wakeup()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle Task.task_wakeup()>
  File "/consumer.py", line 132, in _handle
    self._consumer._process_all_tasks_with_db(
    │    │         └ <function OXConsumer._process_all_tasks_with_db at 0x7fccac6567a0>
    │    └ <__main__.OXConsumer object at 0x7fccae29cc20>
    └ <__main__.SocketGuard object at 0x7fccac64e3c0>
> File "/consumer.py", line 339, in _process_all_tasks_with_db
    run(obj)
    │   └ Object('users/user', 'uid=administrator,cn=users,dc=ucs,dc=test')
    └ <function run at 0x7fccac655300>
  File "/usr/local/lib/python3.13/dist-packages/univention/ox/provisioning/__init__.py", line 107, in run
    modify_user(obj)
    │           └ Object('users/user', 'uid=administrator,cn=users,dc=ucs,dc=test')
    └ <function modify_user at 0x7fccac654f40>
  File "/usr/local/lib/python3.13/dist-packages/univention/ox/provisioning/users.py", line 474, in modify_user
    return create_user(obj)
           │           └ Object('users/user', 'uid=administrator,cn=users,dc=ucs,dc=test')
           └ <function create_user at 0x7fccac654ea0>
  File "/usr/local/lib/python3.13/dist-packages/univention/ox/provisioning/users.py", line 367, in create_user
    user = user_from_attributes(
           └ <function user_from_attributes at 0x7fccac6549a0>
  File "/usr/local/lib/python3.13/dist-packages/univention/ox/provisioning/users.py", line 117, in user_from_attributes
    update_user(user, attributes, old_attributes, username, initial_values)
    │           │     │           │               │         └ True
    │           │     │           │               └ 'Administrator'
    │           │     │           └ {'username': 'Administrator', 'uidNumber': 2002, 'gidNumber': 5000, 'firstname': None, 'lastname': 'Administrator', 'gecos': ...
    │           │     └ {'username': 'Administrator', 'uidNumber': 2002, 'gidNumber': 5000, 'firstname': None, 'lastname': 'Administrator', 'gecos': ...
    │           └ {'aliases': [], 'anniversary': None, 'assistant_name': None, 'birthday': None, 'branches': None, 'business_category': None, '...
    └ <function update_user at 0x7fccac654cc0>
  File "/usr/local/lib/python3.13/dist-packages/univention/ox/provisioning/users.py", line 256, in update_user
    set_ox_property(user, ox_property, mapping, attributes)
    │               │     │            │        └ {'username': 'Administrator', 'uidNumber': 2002, 'gidNumber': 5000, 'firstname': None, 'lastname': 'Administrator', 'gecos': ...
    │               │     │            └ {'ldap_attribute': 'mailPrimaryAddress', 'nillable': False, 'multi_value': False, 'special_handling': 'DEFAULT', 'alternative...
    │               │     └ 'email1'
    │               └ {'aliases': [], 'anniversary': None, 'assistant_name': None, 'birthday': None, 'branches': None, 'business_category': None, '...
    └ <function set_ox_property at 0x7fccac654c20>
  File "/usr/local/lib/python3.13/dist-packages/univention/ox/provisioning/users.py", line 208, in set_ox_property
    logger.warn("Attribute is None.", attribute=ox_property)
    │                                           └ 'email1'
    └ <loguru.logger handlers=[(id=1, level=20, sink=<stdout>)]>
AttributeError: 'Logger' object has no attribute 'warn'

Issue: #0